export const SEQUELIZE = 'SEQUELIZE';
export const DEVELOPMENT = 'development';
export const TEST = 'test';
export const PRODUCTION = 'production';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const TOPIC_REPOSITORY = 'TOPIC_REPOSITORY';
export const MEDIA_REPOSITORY = 'MEDIA_REPOSITORY';
export const TYPE_REPOSITORY = 'TYPE_REPOSITORY';
export const COUNTRY_REPOSITORY = 'COUNTRY_REPOSITORY';
export const TOPIC_REQUEST_CHANGE_REPOSITORY =
  'TOPIC_REQUEST_CHANGE_REPOSITORY';
export const TOPIC_REQUEST_ITEM_REPOSITORY = 'TOPIC_REQUEST_ITEM_REPOSITORY';
