export const SEQUELIZE = 'SEQUELIZE';
export const DEVELOPMENT = 'development';
export const TEST = 'test';
export const PRODUCTION = 'production';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const TOPIC_REPOSITORY = 'TOPIC_REPOSITORY';
export const TOPIC_ITEM_REPOSITORY = 'TOPIC_ITEM_REPOSITORY';
export const TYPE_REPOSITORY = 'TYPE_REPOSITORY';
export const COUNTRY_REPOSITORY = 'COUNTRY_REPOSITORY';
export const TOPIC_REQUEST_CHANGE_REPOSITORY =
  'TOPIC_REQUEST_CHANGE_REPOSITORY';
export const TOPIC_REQUEST_ITEM_REPOSITORY = 'TOPIC_REQUEST_ITEM_REPOSITORY';
export const DISCUSSION_REPOSITORY = 'DISCUSSION_REPOSITORY';
export const MESSAGE_REPOSITORY = 'MESSAGE_REPOSITORY';
export const APP_CONFIG_REPOSITORY = 'APP_CONFIG_REPOSITORY';
